# Form implementation generated from reading ui file '.\GUI\ui_main_work_no_page.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import GUI.res_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        MainWindow.resize(1490, 720)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 720))
        MainWindow.setStyleSheet("#title_bar {\n"
"    background-color: #2C3F44;\n"
"    color: white;\n"
"    height: 40px;\n"
"    font-size: 16pt;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QWidget {\n"
"    background-color: rgba(42, 62, 73, 1);\n"
"}\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #2C3F44;\n"
"    font-weight:bold;\n"
"}")
        MainWindow.setIconSize(QtCore.QSize(20, 20))
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Triangular)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("padding: 5px;")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.icon_name_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.icon_name_widget.setMinimumSize(QtCore.QSize(0, 720))
        self.icon_name_widget.setStyleSheet("QWidget {\n"
"paddind: 5px;\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"     text-align:left;\n"
"     padding-left: 15%;\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #2C3F44;\n"
"    font-weight:bold;\n"
"}")
        self.icon_name_widget.setObjectName("icon_name_widget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.icon_name_widget)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(14)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 7, -1, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_2.setMinimumSize(QtCore.QSize(60, 60))
        self.label_2.setMaximumSize(QtCore.QSize(60, 60))
        self.label_2.setStyleSheet("QLabel {\n"
"    border-radius: 7px;       /* Закруглення країв для створення круглої форми */\n"
"    border: 2px solid #000;   /* Додавання рамки */\n"
"    background-color: none;   /* Відсутність фону */\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QLabel::SetPixmap {\n"
"    border-radius: 7px;       /* Закруглення країв зображення */\n"
"}\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/img/main_icon.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.NoTextInteraction)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.icon_name_widget)
        self.label_3.setMaximumSize(QtCore.QSize(120, 60))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setMouseTracking(False)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.dashboard_button_1 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.dashboard_button_1.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dashboard_button_1.setFont(font)
        self.dashboard_button_1.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/list.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.dashboard_button_1.setIcon(icon)
        self.dashboard_button_1.setIconSize(QtCore.QSize(30, 30))
        self.dashboard_button_1.setCheckable(True)
        self.dashboard_button_1.setAutoExclusive(True)
        self.dashboard_button_1.setObjectName("dashboard_button_1")
        self.verticalLayout_2.addWidget(self.dashboard_button_1)
        self.connect_ftp_button_1 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.connect_ftp_button_1.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.connect_ftp_button_1.setFont(font)
        self.connect_ftp_button_1.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/ftp.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.connect_ftp_button_1.setIcon(icon1)
        self.connect_ftp_button_1.setIconSize(QtCore.QSize(30, 30))
        self.connect_ftp_button_1.setCheckable(True)
        self.connect_ftp_button_1.setAutoExclusive(True)
        self.connect_ftp_button_1.setAutoDefault(False)
        self.connect_ftp_button_1.setObjectName("connect_ftp_button_1")
        self.verticalLayout_2.addWidget(self.connect_ftp_button_1)
        self.addScheduleButton_1 = QtWidgets.QPushButton(parent=self.icon_name_widget)
        self.addScheduleButton_1.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.addScheduleButton_1.setFont(font)
        self.addScheduleButton_1.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/schedule.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.addScheduleButton_1.setIcon(icon2)
        self.addScheduleButton_1.setIconSize(QtCore.QSize(30, 30))
        self.addScheduleButton_1.setCheckable(True)
        self.addScheduleButton_1.setAutoExclusive(True)
        self.addScheduleButton_1.setObjectName("addScheduleButton_1")
        self.verticalLayout_2.addWidget(self.addScheduleButton_1)
        spacerItem = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        self.gridLayout.addWidget(self.icon_name_widget, 0, 1, 1, 1)
        self.content_widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.content_widget.setMinimumSize(QtCore.QSize(0, 700))
        self.content_widget.setStyleSheet("QWidget {\n"
"background-color: rgba(255, 255, 255, 30); \n"
"color: white;\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #2C3F44;\n"
"    font-weight:bold;\n"
"}")
        self.content_widget.setObjectName("content_widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(parent=self.content_widget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.switch_menu_button = QtWidgets.QPushButton(parent=self.widget_4)
        self.switch_menu_button.setMinimumSize(QtCore.QSize(30, 30))
        self.switch_menu_button.setMaximumSize(QtCore.QSize(30, 30))
        self.switch_menu_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.switch_menu_button.setIcon(icon3)
        self.switch_menu_button.setIconSize(QtCore.QSize(22, 22))
        self.switch_menu_button.setCheckable(True)
        self.switch_menu_button.setObjectName("switch_menu_button")
        self.horizontalLayout_3.addWidget(self.switch_menu_button)
        spacerItem1 = QtWidgets.QSpacerItem(468, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search = QtWidgets.QLineEdit(parent=self.widget_4)
        self.search.setMinimumSize(QtCore.QSize(0, 30))
        self.search.setMaximumSize(QtCore.QSize(16777215, 30))
        self.search.setObjectName("search")
        self.horizontalLayout_2.addWidget(self.search)
        self.search_button = QtWidgets.QPushButton(parent=self.widget_4)
        self.search_button.setMinimumSize(QtCore.QSize(30, 30))
        self.search_button.setMaximumSize(QtCore.QSize(30, 30))
        self.search_button.setStyleSheet("QPushButton::pressed {\n"
"background-color: rgba(42, 62, 73, 1);\n"
"}")
        self.search_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/img/search.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_button.setIcon(icon4)
        self.search_button.setIconSize(QtCore.QSize(22, 22))
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.content_widget)
        self.stackedWidget.setStyleSheet("QLineEdit, QComboBox {\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"     text-align:left;\n"
"     padding-left: 15%;\n"
"    font-size: 16pt;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"    width: 120;\n"
"    height: 45;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dashboard_page = QtWidgets.QWidget()
        self.dashboard_page.setStyleSheet("QPushButton:pressed{\n"
"    background-color: #2C3F44;\n"
"    font-weight:bold;\n"
"}")
        self.dashboard_page.setObjectName("dashboard_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.dashboard_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 2)
        self.verticalLayout_6.setSpacing(10)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.dashboard_page)
        self.tableWidget.setStyleSheet("QTableWidget {\n"
"    padding: 5px;\n"
"    border: 1px solid rgba(255, 255, 255, 40);\n"
"    border-radius: 7px;\n"
"    gridline-color: transparent;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    width: 30px;\n"
"    text-align: left;\n"
"    padding-left: 5px;\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 40);\n"
"}\n"
"QTableView::item:selected{\n"
"    color: rgb(255, 255, 255);\n"
"    font-weight:bold;\n"
"    background-color: rgba(42, 62, 73, 1);;\n"
"}\n"
"QTableWidget::item:first-child {\n"
"    border-left: 7px; /* Заокруглення для верхнього правого кута */\n"
"}\n"
"\n"
"QTableWidget::item:last-child {\n"
"    border-right: 7px; /* Заокруглення для нижнього правого кута */\n"
"}\n"
"\n"
"QHeaderView {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: none; /* Виберіть color: black; або потрібний вам колір */\n"
"    margin: 0px;\n"
"    padding: 0px;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    color: none; /* Виберіть color: white; або потрібний вам колір */\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 40);\n"
"    border-radius: 7px;\n"
"    margin: 5px;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QHeaderView::section:horizontal {\n"
"    background-color: rgba(42, 62, 73, 1);\n"
"    color: white;\n"
"    width: 30px;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QHeaderView::section:vertical {\n"
"    background-color: rgba(42, 62, 73, 1);\n"
"    color: white;\n"
"    width: 20px;\n"
"    height: 50px;\n"
"    font-size: 12pt;\n"
"    text-align: center;\n"
"    padding-left: 12px;\n"
"}\n"
"\n"
"QTableCornerButton::section {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"\n"
"QTableCornerButton {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"    border: none;\n"
"}\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_6.addWidget(self.tableWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, -1, -1, 7)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.add_device_1 = QtWidgets.QPushButton(parent=self.dashboard_page)
        self.add_device_1.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_device_1.setFont(font)
        self.add_device_1.setStyleSheet("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/img/add-list.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_device_1.setIcon(icon5)
        self.add_device_1.setIconSize(QtCore.QSize(30, 30))
        self.add_device_1.setCheckable(False)
        self.add_device_1.setAutoExclusive(False)
        self.add_device_1.setObjectName("add_device_1")
        self.horizontalLayout_6.addWidget(self.add_device_1)
        self.change_device_1 = QtWidgets.QPushButton(parent=self.dashboard_page)
        self.change_device_1.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.change_device_1.setFont(font)
        self.change_device_1.setStyleSheet("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/img/alter.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.change_device_1.setIcon(icon6)
        self.change_device_1.setIconSize(QtCore.QSize(30, 30))
        self.change_device_1.setCheckable(False)
        self.change_device_1.setAutoExclusive(False)
        self.change_device_1.setObjectName("change_device_1")
        self.horizontalLayout_6.addWidget(self.change_device_1)
        self.delete_device_1 = QtWidgets.QPushButton(parent=self.dashboard_page)
        self.delete_device_1.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delete_device_1.setFont(font)
        self.delete_device_1.setStyleSheet("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/img/trash.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.delete_device_1.setIcon(icon7)
        self.delete_device_1.setIconSize(QtCore.QSize(30, 30))
        self.delete_device_1.setCheckable(False)
        self.delete_device_1.setAutoExclusive(False)
        self.delete_device_1.setObjectName("delete_device_1")
        self.horizontalLayout_6.addWidget(self.delete_device_1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.dashboard_page)
        self.pushButton_3.setMinimumSize(QtCore.QSize(160, 60))
        self.pushButton_3.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_6.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.dashboard_page)
        self.pushButton_4.setMinimumSize(QtCore.QSize(160, 60))
        self.pushButton_4.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_6.addWidget(self.pushButton_4)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.dashboard_page)
        self.add_device_page = QtWidgets.QWidget()
        self.add_device_page.setObjectName("add_device_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.add_device_page)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_4 = QtWidgets.QLabel(parent=self.add_device_page)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"font-weight:bold;\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_7.addWidget(self.label_4)
        self.back_dashdoard_button = QtWidgets.QPushButton(parent=self.add_device_page)
        self.back_dashdoard_button.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_dashdoard_button.sizePolicy().hasHeightForWidth())
        self.back_dashdoard_button.setSizePolicy(sizePolicy)
        self.back_dashdoard_button.setMinimumSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button.setMaximumSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button.setStyleSheet("background: none;\n"
"border: none;")
        self.back_dashdoard_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/img/back-button.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_dashdoard_button.setIcon(icon8)
        self.back_dashdoard_button.setIconSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button.setCheckable(False)
        self.back_dashdoard_button.setAutoExclusive(False)
        self.back_dashdoard_button.setObjectName("back_dashdoard_button")
        self.horizontalLayout_7.addWidget(self.back_dashdoard_button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        spacerItem5 = QtWidgets.QSpacerItem(947, 57, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.device_name_text = QtWidgets.QLineEdit(parent=self.add_device_page)
        self.device_name_text.setMinimumSize(QtCore.QSize(0, 60))
        self.device_name_text.setMaximumSize(QtCore.QSize(16777215, 60))
        self.device_name_text.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.device_name_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.device_name_text.setObjectName("device_name_text")
        self.verticalLayout_3.addWidget(self.device_name_text)
        self.rtsp_string_text = QtWidgets.QLineEdit(parent=self.add_device_page)
        self.rtsp_string_text.setMinimumSize(QtCore.QSize(0, 60))
        self.rtsp_string_text.setMaximumSize(QtCore.QSize(16777215, 60))
        self.rtsp_string_text.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.rtsp_string_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rtsp_string_text.setObjectName("rtsp_string_text")
        self.verticalLayout_3.addWidget(self.rtsp_string_text)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.folder_path_text = QtWidgets.QLineEdit(parent=self.add_device_page)
        self.folder_path_text.setMinimumSize(QtCore.QSize(0, 60))
        self.folder_path_text.setMaximumSize(QtCore.QSize(16777215, 60))
        self.folder_path_text.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.folder_path_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.folder_path_text.setObjectName("folder_path_text")
        self.horizontalLayout_4.addWidget(self.folder_path_text)
        self.select_folder = QtWidgets.QPushButton(parent=self.add_device_page)
        self.select_folder.setMinimumSize(QtCore.QSize(60, 60))
        self.select_folder.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.select_folder.setFont(font)
        self.select_folder.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/img/cursor.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.select_folder.setIcon(icon9)
        self.select_folder.setIconSize(QtCore.QSize(30, 30))
        self.select_folder.setObjectName("select_folder")
        self.horizontalLayout_4.addWidget(self.select_folder)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.comboBox = QtWidgets.QComboBox(parent=self.add_device_page)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout_3.addWidget(self.comboBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.add_new_device_button = QtWidgets.QPushButton(parent=self.add_device_page)
        self.add_new_device_button.setMinimumSize(QtCore.QSize(200, 60))
        self.add_new_device_button.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_new_device_button.setFont(font)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/img/save.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.add_new_device_button.setIcon(icon10)
        self.add_new_device_button.setObjectName("add_new_device_button")
        self.horizontalLayout_5.addWidget(self.add_new_device_button)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        spacerItem9 = QtWidgets.QSpacerItem(947, 57, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.add_device_page)
        self.change_device_page = QtWidgets.QWidget()
        self.change_device_page.setObjectName("change_device_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.change_device_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_6 = QtWidgets.QLabel(parent=self.change_device_page)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(255, 255, 255);\n"
"background-color: none;\n"
"font-weight:bold;\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_10.addWidget(self.label_6)
        self.back_dashdoard_button_2 = QtWidgets.QPushButton(parent=self.change_device_page)
        self.back_dashdoard_button_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.back_dashdoard_button_2.sizePolicy().hasHeightForWidth())
        self.back_dashdoard_button_2.setSizePolicy(sizePolicy)
        self.back_dashdoard_button_2.setMinimumSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button_2.setMaximumSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button_2.setStyleSheet("background: none;\n"
"border: none;")
        self.back_dashdoard_button_2.setText("")
        self.back_dashdoard_button_2.setIcon(icon8)
        self.back_dashdoard_button_2.setIconSize(QtCore.QSize(60, 60))
        self.back_dashdoard_button_2.setCheckable(False)
        self.back_dashdoard_button_2.setAutoExclusive(False)
        self.back_dashdoard_button_2.setObjectName("back_dashdoard_button_2")
        self.horizontalLayout_10.addWidget(self.back_dashdoard_button_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtWidgets.QSpacerItem(947, 74, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem10)
        self.device_name_text_2 = QtWidgets.QLineEdit(parent=self.change_device_page)
        self.device_name_text_2.setMinimumSize(QtCore.QSize(0, 60))
        self.device_name_text_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.device_name_text_2.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.device_name_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.device_name_text_2.setObjectName("device_name_text_2")
        self.verticalLayout_4.addWidget(self.device_name_text_2)
        self.rtsp_string_text_2 = QtWidgets.QLineEdit(parent=self.change_device_page)
        self.rtsp_string_text_2.setMinimumSize(QtCore.QSize(0, 60))
        self.rtsp_string_text_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.rtsp_string_text_2.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.rtsp_string_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.rtsp_string_text_2.setObjectName("rtsp_string_text_2")
        self.verticalLayout_4.addWidget(self.rtsp_string_text_2)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.folder_path_text_2 = QtWidgets.QLineEdit(parent=self.change_device_page)
        self.folder_path_text_2.setMinimumSize(QtCore.QSize(0, 60))
        self.folder_path_text_2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.folder_path_text_2.setStyleSheet("font-size: 16pt;\n"
"color: white;\n"
"padding-left: 10px;\n"
"width: 120;\n"
"height: 45;")
        self.folder_path_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.folder_path_text_2.setObjectName("folder_path_text_2")
        self.horizontalLayout_9.addWidget(self.folder_path_text_2)
        self.select_folder_2 = QtWidgets.QPushButton(parent=self.change_device_page)
        self.select_folder_2.setMinimumSize(QtCore.QSize(60, 60))
        self.select_folder_2.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.select_folder_2.setFont(font)
        self.select_folder_2.setText("")
        self.select_folder_2.setIcon(icon9)
        self.select_folder_2.setIconSize(QtCore.QSize(30, 30))
        self.select_folder_2.setObjectName("select_folder_2")
        self.horizontalLayout_9.addWidget(self.select_folder_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.change_device_page)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_4.addWidget(self.comboBox_2)
        spacerItem11 = QtWidgets.QSpacerItem(1048, 74, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem12)
        self.add_new_device_button_2 = QtWidgets.QPushButton(parent=self.change_device_page)
        self.add_new_device_button_2.setMinimumSize(QtCore.QSize(200, 60))
        self.add_new_device_button_2.setMaximumSize(QtCore.QSize(200, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_new_device_button_2.setFont(font)
        self.add_new_device_button_2.setIcon(icon10)
        self.add_new_device_button_2.setObjectName("add_new_device_button_2")
        self.horizontalLayout_8.addWidget(self.add_new_device_button_2)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        spacerItem14 = QtWidgets.QSpacerItem(947, 74, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem14)
        self.stackedWidget.addWidget(self.change_device_page)
        self.connect_ftp_page = QtWidgets.QWidget()
        self.connect_ftp_page.setObjectName("connect_ftp_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.connect_ftp_page)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(parent=self.connect_ftp_page)
        font = QtGui.QFont()
        font.setPointSize(32)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.connect_ftp_page)
        self.add_schedule_page = QtWidgets.QWidget()
        self.add_schedule_page.setObjectName("add_schedule_page")
        self.stackedWidget.addWidget(self.add_schedule_page)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.content_widget, 0, 2, 1, 1)
        self.icon_widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(70)
        sizePolicy.setHeightForWidth(self.icon_widget.sizePolicy().hasHeightForWidth())
        self.icon_widget.setSizePolicy(sizePolicy)
        self.icon_widget.setMinimumSize(QtCore.QSize(70, 720))
        self.icon_widget.setStyleSheet("QWidget {\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(255, 255, 255);\n"
"     background-color:rgba(255,255,255,30);\n"
"     border: 1px solid rgba(255,255,255,40);\n"
"     border-radius:7px;\n"
"     text-align:left;\n"
"     padding-left: 15%;\n"
"width: 230;\n"
"height: 50;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:rgba(255,255,255,30);\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:rgba(255,255,255,70);\n"
"}\n"
"QPushButton:checked{\n"
"    background-color: #2C3F44;\n"
"    font-weight:bold;\n"
"}")
        self.icon_widget.setObjectName("icon_widget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.icon_widget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, 0, 0)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.icon_widget)
        self.label.setMinimumSize(QtCore.QSize(60, 60))
        self.label.setMaximumSize(QtCore.QSize(50, 50))
        self.label.setStyleSheet("QLabel {\n"
"    border-radius: 7px;       /* Закруглення країв для створення круглої форми */\n"
"    border: 2px solid #000;   /* Додавання рамки */\n"
"    background-color: none;   /* Відсутність фону */\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QLabel::SetPixmap {\n"
"    border-radius: 7px;       /* Закруглення країв зображення */\n"
"}\n"
"")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/main_icon.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dashboard_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.dashboard_button.setMinimumSize(QtCore.QSize(60, 60))
        self.dashboard_button.setMaximumSize(QtCore.QSize(60, 60))
        self.dashboard_button.setStyleSheet("")
        self.dashboard_button.setText("")
        self.dashboard_button.setIcon(icon)
        self.dashboard_button.setIconSize(QtCore.QSize(30, 30))
        self.dashboard_button.setCheckable(True)
        self.dashboard_button.setAutoExclusive(True)
        self.dashboard_button.setObjectName("dashboard_button")
        self.verticalLayout.addWidget(self.dashboard_button)
        self.connect_ftp_button = QtWidgets.QPushButton(parent=self.icon_widget)
        self.connect_ftp_button.setMinimumSize(QtCore.QSize(60, 60))
        self.connect_ftp_button.setMaximumSize(QtCore.QSize(60, 60))
        self.connect_ftp_button.setStyleSheet("")
        self.connect_ftp_button.setText("")
        self.connect_ftp_button.setIcon(icon1)
        self.connect_ftp_button.setIconSize(QtCore.QSize(30, 30))
        self.connect_ftp_button.setCheckable(True)
        self.connect_ftp_button.setAutoExclusive(True)
        self.connect_ftp_button.setAutoDefault(False)
        self.connect_ftp_button.setObjectName("connect_ftp_button")
        self.verticalLayout.addWidget(self.connect_ftp_button)
        self.addScheduleButton = QtWidgets.QPushButton(parent=self.icon_widget)
        self.addScheduleButton.setMinimumSize(QtCore.QSize(60, 60))
        self.addScheduleButton.setMaximumSize(QtCore.QSize(60, 60))
        self.addScheduleButton.setStyleSheet("")
        self.addScheduleButton.setText("")
        self.addScheduleButton.setIcon(icon2)
        self.addScheduleButton.setIconSize(QtCore.QSize(30, 30))
        self.addScheduleButton.setCheckable(True)
        self.addScheduleButton.setAutoExclusive(True)
        self.addScheduleButton.setObjectName("addScheduleButton")
        self.verticalLayout.addWidget(self.addScheduleButton)
        spacerItem15 = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem15)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.icon_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        self.switch_menu_button.toggled['bool'].connect(self.icon_widget.setHidden) # type: ignore
        self.switch_menu_button.toggled['bool'].connect(self.icon_name_widget.setVisible) # type: ignore
        self.dashboard_button.toggled['bool'].connect(self.dashboard_button_1.setChecked) # type: ignore
        self.connect_ftp_button.toggled['bool'].connect(self.connect_ftp_button_1.setChecked) # type: ignore
        self.addScheduleButton.toggled['bool'].connect(self.addScheduleButton_1.setChecked) # type: ignore
        self.dashboard_button_1.toggled['bool'].connect(self.dashboard_button.setChecked) # type: ignore
        self.connect_ftp_button_1.toggled['bool'].connect(self.connect_ftp_button.setChecked) # type: ignore
        self.addScheduleButton_1.toggled['bool'].connect(self.addScheduleButton.setChecked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Menu"))
        self.dashboard_button_1.setText(_translate("MainWindow", "Dashboard"))
        self.connect_ftp_button_1.setText(_translate("MainWindow", "Connect FTP"))
        self.addScheduleButton_1.setText(_translate("MainWindow", "Add schedule"))
        self.add_device_1.setText(_translate("MainWindow", "Add device"))
        self.change_device_1.setText(_translate("MainWindow", "Change device"))
        self.delete_device_1.setText(_translate("MainWindow", "Delete Device"))
        self.pushButton_3.setText(_translate("MainWindow", "Stop"))
        self.pushButton_4.setText(_translate("MainWindow", "Start"))
        self.label_4.setText(_translate("MainWindow", "      Add device"))
        self.device_name_text.setPlaceholderText(_translate("MainWindow", "Name"))
        self.rtsp_string_text.setPlaceholderText(_translate("MainWindow", "RTSP string"))
        self.folder_path_text.setPlaceholderText(_translate("MainWindow", "Path to folder"))
        self.add_new_device_button.setText(_translate("MainWindow", "Save"))
        self.label_6.setText(_translate("MainWindow", "      Change device"))
        self.device_name_text_2.setPlaceholderText(_translate("MainWindow", "Name"))
        self.rtsp_string_text_2.setPlaceholderText(_translate("MainWindow", "RTSP string"))
        self.folder_path_text_2.setPlaceholderText(_translate("MainWindow", "Path to folder"))
        self.add_new_device_button_2.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "SOON"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
